spring:
 profiles.active: local
   
---
spring:
 profiles: local
 datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/kaligia
  username: ${DB_USERID:postgres}
  password: ${DB_PASSWD:postgres}
  accessToUnderlyingConnectionAllowed: true
 config:
  location: /mapper/*.xml
server:
 port: 8090
mybatis:
  mapper-locations:
    0: mapper/kaligia/DeviceMapper.xml
    1: mapper/kaligia/DeviceSpecMapper.xml
    2: mapper/kaligia/LabLogMapper.xml
    3: mapper/kaligia/OrderDetailsMapper.xml
    4: mapper/kaligia/ProcSegmentMapper.xml
    5: mapper/kaligia/RunOrderMapper.xml
    6: mapper/kaligia/RunSegmentLogMapper.xml
    7: mapper/kaligia/RunSegmentMapper.xml
    8: mapper/kaligia/SiteMapper.xml
    9: mapper/kaligia/SpecimenMapper.xml
    10: mapper/kaligia/SpecimenSpecMapper.xml
    11: mapper/kaligia/SubjectLogMapper.xml
    12: mapper/kaligia/SubjectMapper.xml
    13: mapper/kaligia/TestDevicesMapper.xml
    14: mapper/kaligia/TestOrderMapper.xml
    15: mapper/kaligia/TestProcedureMapper.xml
    16: mapper/kaligia/TestSegmentMapper.xml
    17: mapper/kaligia/TestSegmentSpecMapper.xml
    18: mapper/kaligia/UsersMapper.xml
    19: mapper/kaligia/TmpTestResultMapper.xml
    20: mapper/kaligia/DeviceInstMapper.xml
    21: mapper/kaligia/EndPointMapper.xml
    22: mapper/kaligia/EndPointDevicesMapper.xml
    23: mapper/kaligia/EndPointProcsMapper.xml
    24: mapper/kaligia/PrivilegesMapper.xml
    25: mapper/kaligia/RolePrivsMapper.xml
    26: mapper/kaligia/RolesMapper.xml
    27: mapper/kaligia/RunDevicesMapper.xml
    28: mapper/kaligia/FLRemovedLogMapper.xml
    29: mapper/kaligia/TestProcedureSpecsMapper.xml
    30: mapper/kaligia/AppConfigMapper.xml


---
spring:
 profiles: development
 datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.1.135:5432/kaligia
  username: ${DB_USERID:postgres}
  password: ${DB_PASSWD:postgres}
  accessToUnderlyingConnectionAllowed: true
  max-active: 25
  max-idle: 10
  min-idle: 1
  initial-size: 1
  validation-query: "SELECT 1 FROM DUAL"
  test-on-borrow: true
 config:
  location: /mapper
server:
 port: 80
  